{
 "title": "SCADA_ESTIMADOR_PostgreSQL",
 "time": { "from": "now+40m", "to": "now+1h" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Active Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "select Date_Time, \r\nPOI_P AS \"POI_P\",\r\nCT1_P AS \"SS1_P\",\r\nCT2_P AS \"SS2_P\"\r\nfrom DB_CSL_BROKER_INPUT"
    },
    {
     "rawSql": "select Date_Time, \r\nP_POI_POI AS \"POI_P_EST\",\r\nP_SS1_SS2 AS \"SS1_P_EST\",\r\nP_SS2_POI AS \"SS2_P_EST\"\r\nfrom DB_CSL_BROKER_OUTPUT"
    }
   ]
  },
  {
   "title": "Reactive Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "targets": [
    {
     "rawSql": "select Date_Time, \r\nPOI_Q AS \"POI_Q\",\r\nCT1_Q AS \"SS1_Q\",\r\nCT2_Q AS \"SS2_Q\"\r\nfrom DB_CSL_BROKER_INPUT"
    },
    {
     "rawSql": "select Date_Time, \r\nQ_POI_POI AS \"POI_Q_EST\",\r\nQ_SS1_SS2 AS \"SS1_Q_EST\",\r\nQ_SS2_POI AS \"SS2_Q_EST\"\r\nfrom DB_CSL_BROKER_OUTPUT"
    }
   ]
  },
  {
   "title": "VOLTAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "select Date_Time, \r\nPOI_Va AS \"POI_V\",\r\nCT1_Vab AS \"SS1_V\",\r\nCT2_Vab AS \"SS2_V\"\r\nfrom DB_CSL_BROKER_INPUT"
    },
    {
     "rawSql": "select Date_Time, \r\nV_POI_EST AS \"POI_V_EST\",\r\nV_SS1_EST AS \"SS1_V_EST\",\r\nV_SS2_EST AS \"SS2_V_EST\"\r\nfrom DB_CSL_BROKER_OUTPUT"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "select Date_Time, \r\nP_POI_POI AS \"POI_P_EST\",\r\nP_SS1_SS2 AS \"SS1_P_EST\",\r\nP_SS2_POI AS \"SS2_P_EST\"\r\nfrom DB_CSL_BROKER_OUTPUT"
    },
    {
     "rawSql": "select Date_Time, \r\nPOI_P AS \"POI_P\",\r\nCT1_P AS \"SS1_P\",\r\nCT2_P AS \"SS2_P\"\r\nfrom DB_CSL_BROKER_INPUT"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "select Date_Time, \r\nPOI_Va AS \"POI_V\",\r\nPOI_F AS \"POI_F\",\r\nPOI_P AS \"POI_P\",\r\nPOI_Q AS \"POI_Q\",\r\nCT1_Vab AS \"CT1_V\",\r\nCT1_P AS \"CT1_P\",\r\nCT1_Q AS \"CT1_Q\",\r\nCT1_P_REF AS \"CT1_Pref\",\r\nCT1_Q_REF AS \"CT1_Qref\",\r\nCT2_Vab AS \"CT2_V\",\r\nCT2_P AS \"CT2_P\",\r\nCT2_Q AS \"CT2_Q\",\r\nCT2_P_REF AS \"CT2_Pref\",\r\nCT2_Q_REF AS \"CT2_Qref\"\r\nfrom DB_CSL_BROKER_INPUT"
    },
    {
     "rawSql": "select Date_Time, \r\nV_POI_EST AS \"POI_V_EST\",\r\nP_POI_POI AS \"POI_P_EST\",\r\nQ_POI_POI AS \"POI_Q_EST\",\r\nV_SS1_EST AS \"SS1_V_EST\",\r\nP_SS1_SS2 AS \"SS1_P_EST\",\r\nQ_SS1_SS2 AS \"SS1_Q_EST\",\r\nV_SS2_EST AS \"SS2_V_EST\",\r\nP_SS2_POI AS \"SS2_P_EST\",\r\nQ_SS2_POI AS \"SS2_Q_EST\"\r\nfrom DB_CSL_BROKER_OUTPUT"
    }
   ]
  }
 ]
}